version: "3"
services:
  web:
    #    image: 192.168.5.13:9000/web/gwbs:offline_v2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    volumes:
      - ../data:/wwwroot/logs
    environment:
      "PROJECT_ENV": "pro"
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      "POSTGRES_PASSWORD": "aHfOQhnsPSSlOFcHeDL2"
      "POSTGRES_USER": "gwbs"